name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install deps
      run: >
        sudo apt-get update &&
        sudo apt-get install -y build-essential git tar curl nodejs npm &&
        sudo npm install --global yarn

    - name: Setup .env
      run: >
        echo "API_USERNAME=$API_USERNAME" >> .env &&
        echo "API_TOKEN=$API_TOKEN" >> .env

    - name: Install upx
      run: make install_upx

    - name: Build
      run: make web build upx
